SUCCESSFUL_CREATION = "Successfully created"
STATUS_UPDATION_SUCCESSFUL = "Status updated successfully"
STATUS_UPDATION_FAILURE = "Status not updated"
MISSING_KEYS_ERROR = "Required keys are missing"
INCORRECT_DATATYPE_ERROR = "Required values data type are incorrect"
DEFAULT_ERROR_MESSAGE = "Some error occured while executing process"
